### ISSUE TITLE
[FR] - Retrieve Cardano node version with Cardano CLI

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/cardano-cli#224]
**Internal/External**
*Internal*   Mithril team

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
The Mithril team would like to provide the version of the Cardano node used to create snapshots of the internal database. 
In order to do so, we would need to retrieve this information through the Cardano CLI. 
It seems that there used to be a `cardano-cli node version` command in previous versions of the CLI that has since been deprecated.

We would need, as an example, to get access to a CLI command to retrieve the version of the Cardano node like this one:
```bash
$ cardano-cli node version --cardano-node-socket-path <PATH_TO_NODE_SOCKET>
cardano-node 8.1.2 - linux-x86_64 - ghc-8.10
git rev 0000000000000000000000000000000000000000
```

Many thanks for your help :smile:

**Comment by jpraynaud** [comment]
Ping @abailly-iohk @rezabaram

**Comment by nfrisby** [comment]
If, to enable this, we were to add a query to the Consensus layer that simply echoes back whatever data the Node layer passed to the Consensus layer when originally invoking it, what type should that have? Would `Aeson.Value` be wise? Or would we want to do more validation on start-up and/or support a set of very specific strongly-typed queries?

cc @carbolymer @dnadales

**Comment by carbolymer** [comment]
I'm thinking maybe it would be nice to expand this also with more health information and stuff like OS, architecture, protocol version. Having a concrete type would make rendering a bit easier. 
On the other hand if the query would just return `Value`, we can serialize and de-serialize the value in cardano-api (just making sure to keep backwards compatibility) and make the implementation easier.
@Jimbo4350 what do you think, what else could be useful to have here?

**Comment by smelc** [comment]
Hey @carbolymer, new cardano-cli developer here :wave: (started yesterday)

I was crawling issues to see where I could start contributing and was actually considering this one when @nfrisby's and your comment showed up. Do you think it's one I could give a try?

**Comment by dcoutts** [comment]
> version of the Cardano node used to create snapshots of the internal database

I presume you want to know this as a proxy for the format of the database.

This is very intimate with this specific implementation of the node (i.e. would have to do something different with a protocol-compatible 3rd party impl). So why not just ask the node directly:
```
$ carcano-node --version
```

**Comment by nfrisby** [comment]
@dcoutts I had that some suspicion. I figured they favor `cardano-cli` for a few reasonable reasons, one of which might be that there's no guarantee that the in-`$PATH` `cardano-node` exe is the same as whichever node process `cardano-cli` is communicating with 🤷

**Comment by nfrisby** [comment]
Yeah, my interest in something like `Aeson.Value` is so that any additions to this info could be maintained and versioned downstream, without having to churn the Consensus interface/implementation... since the Consensus-level semantics of this field are simply "pass through".

**Comment by ghost** [comment]
@nfrisby We of course don't really care about the implementation details, but having some kind of schema of what a client can expect would be nice.

@dcoutts Sure, that could be an option, but it's quite usual in servers to provide some version information through their standard API in order to ease the work of clients to understand whether or not they can work with this particular version. Right now, the need from Mithril perspective is to provide a way to let clients know what to expect from the data they retrieve, eg. whether or not the version of the node they are using will be able to take advantage of the snapshot they downloaded. But it's not a big stretch to extend that usage to the actual data be signed, eg. should we want to provide mithril certificates for some piece of data that's only available from some version onward. 

Also, we already use the `cardano-cli` as a surrogate for a proper use of the node's API and are planning to replace that with direct connection in the near future. Having to revert to call an executable and parse its output would seem to be backwards, not speaking of the usual issues of path resolution.

**Comment by dcoutts** [comment]
@abailly-iohk but on the other hand, we usually make APIs/protocols that are capable of multiple independent implementations (excepting debug "dumb the whole ledger state" things), and reporting an implementation version rather than a protocol version goes against that. And what you're doing is not trying to be portable anyway. At least not at the moment (until we get to some portable format for snapshots, which I'd like to see some day).

> eg. should we want to provide mithril certificates for some piece of data that's only available from some version onward.

That would be a protocol version (not implementation version), and that's totally ok, and you get that already when you do the protocol version negotiation. That is, when you do the connection to the node yourself. The cli could also in principle have a query that just reports the latest (and perhaps earliest) supported client protocol versions. That wouldn't need any node extensions.

Consider if you can do what you need with the node->client _protocol version_ rather than the node implementation version. If so, that's a much nicer solution in principle.

**Comment by ghost** [comment]
I agree working with the protocol version would be conceptually nicer. Yet in practice the snapshot we are building, signing, and distributing is _currently_ relevant to the current cardano-node implementation version, hence why we would like to have that information in order to help clients using those snapshots to understand the consequences of using this or that snapshot. And there's no other node implementation anyway. 

In essence, every snapshot we manage to sign might have different rules, and different versions, and that's fine. In the future, should we sign say the UTxO set, adding the protocol version as part of the snapshot would be useful _and_ portable.

**Comment by dcoutts** [comment]
So if you're not pretending to be portable, just ask the node for its version number: `cardano-node --version`.

**Comment by ghost** [comment]
For the reasons I exposed above, this is annoying but 🤷
