### ISSUE TITLE
Convert a dRep extended vkey to a non-extended one:

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#358]
```console
cardano-cli conway key non-extended-key --extended-verification-key-file test.drep.vkey --verification-key-file /dev/stdout

Command failed: key non-extended-key  Error: Invalid key.
```

_Originally posted by @gitmachtl in https://github.com/input-output-hk/cardano-cli/issues/352#issuecomment-1753622844_

**Comment by smelc** [comment]
@CarlosLopezDeLara> in this case, the original extended drep key should be created as follows right?

```shell
cabal run cardano-cli -- conway governance drep key-gen \
--verification-key-file drep.vkey \
--signing-key-file drep.skey
```

**Comment by gitmachtl** [comment]
@smelc no need for cardano-cli to generate extended drep keys. they are coming into play if derived from the new path 1852'/1815'/acc'/3/idx'. typically from 3rd party tools like cardano-signer, spo-scripts, cardano-address, cardano-hw-cli.


https://github.com/Ryun1/CIPs/blob/conway-keys/CIP-conway-keys/README.md
https://github.com/cardano-foundation/CIPs/pull/509

**Comment by CarlosLopezDeLara** [comment]
@smelc, as @gitmachtl rightly pointed out, extended keys typically come from Hierarchical deterministic (HD) key generation tools, so the cli doesn't generete them, just supports them. 

In this case we want to be able to convert from extended to non-extended keys. 

Additionaly, in #352 there is the need of support the use of extended keys directly on cli without having to convert them first.

**Comment by smelc** [comment]
@gitmachtl, @CarlosLopezDeLara> OK I see, thanks for the explanations :+1:

As a first step, for this very specific issue, could one of you provide me with an example extended key (in your example Carlos the `test.drep.vkey` file)? Just so that I see if I can reproduce the issue locally, which will help me navigate what I need to do.

**Comment by gitmachtl** [comment]
@smelc you can simply copy the test key below and paste it into a textfile:
```json
{
  "type": "DRepExtendedVerificationKey_ed25519_bip32",
  "description": "Delegate Representative Verification Key",
  "cborHex": "5840b0cd9e6e3e274f4f38f55ef274af123cf4600ac0c58294399b7e076175262553dde8b75f847f2b7e61a8748627292a06d739c8ba8e78ac83e666030d1093fb3e"
}
```

i have uploaded you the same file [here](https://my-ip.at/test/test.drep.vkey) if needed

**Comment by smelc** [comment]
Investigating this this morning. The offending code starts with the parser at [Cardano/CLI/Legacy/Run/Key.hs#L53](https://github.com/input-output-hk/cardano-cli/blob/c3193e6020f740fcaab701254737fd2d9ef40630/cardano-cli/src/Cardano/CLI/Legacy/Run/Key.hs#L53) then goes on with [Cardano/CLI/EraBased/Run/Key.hs#L138](https://github.com/input-output-hk/cardano-cli/blob/c3193e6020f740fcaab701254737fd2d9ef40630/cardano-cli/src/Cardano/CLI/EraBased/Run/Key.hs#L138). Finally it calls [Cardano/CLI/Types/Key.hs#L251](https://github.com/input-output-hk/cardano-cli/blob/c3193e6020f740fcaab701254737fd2d9ef40630/cardano-cli/src/Cardano/CLI/Types/Key.hs#L251) at which point it goes to code in `cardano-api`.

**Comment by smelc** [comment]
Going into cardano-api, we find our friend `deserializeAnyVerificationKey` in [cardano-api/internal/Cardano/Api/DeserialiseAnyOf.hs#L299](https://github.com/input-output-hk/cardano-api/blob/dfb2a8f6a325f27985651c6388b54a3fd8d9e951/cardano-api/internal/Cardano/Api/DeserialiseAnyOf.hs#L299) and finally we find in [cardano-api/internal/Cardano/Api/Keys/Shelley.hs#L1493](https://github.com/input-output-hk/cardano-api/blob/dfb2a8f6a325f27985651c6388b54a3fd8d9e951/cardano-api/internal/Cardano/Api/Keys/Shelley.hs#L1493) that there is no `Extended` version of `DRepKey`, which is likely the crux of the problem.

I know need to figure out how it's formally defined, so that I can add the corresponding code.

**Comment by gitmachtl** [comment]
@ryun1 @CarlosLopezDeLara i think we had this in a pr from you. also its in the cip-conway-keys: https://github.com/Ryun1/CIPs/blob/conway-keys/CIP-conway-keys/README.md
