### ISSUE TITLE
replace --stake-verification-key-file with --deposit-return-stake-verification-key-file on all action commands

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#422]
We disambiguated treasury withdrawals which require 2 stake credentials with `--deposit-return-stake-verification-key-file` and `--funds-receiving-stake-verification-key-file`. 

Well, users will appreciate if we have the same clarity on all other action commands, so we want to replace the existing `--stake-verification-key-file` flag with the more descriptive  `--deposit-return-stake-verification-key-file` on all other governance actions

The same for `--stake-verification-key` and `--stake-verification-key-hash`

Replaced with 

`--deposit-return-stake-verification-key` and 

`--deposit-return-stake-verification-key-hash`, respectively.

**Comment by smelc** [comment]
Marking _blocked_, because solving this issue will affect the same places as:

* https://github.com/input-output-hk/cardano-cli/pull/442
* https://github.com/input-output-hk/cardano-cli/issues/447

So those two should be tackled first, to avoid merge conflicts hell. This will happen soon, so no worries about getting to this one soon.

**Comment by smelc** [comment]
Looking at `--stake-verification-key-file`, I believe the occurrences to change are as follows (red arrows):

![image](https://github.com/input-output-hk/cardano-cli/assets/634720/b81baaec-fb76-4b77-b876-46ffb6eb0d26)

I'm omitting:

1. the `pStakeAddressCmds` caller in `Cardano.CLI.Legacy.Options`, because it's legacy.
2. the `pGovernanceActionTreasuryWithdrawalCmd` caller. This one has been changed already, as stated in the issue's description.
3. the `pStakeVerifier` caller in `Cardano.CLI.Erabased.Options.Cmd`, because it goes into non-governance commands.
