### ISSUE TITLE
stake-address-info to show drep-delegation

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#423]
Currently, the stake-address-info shows:

```
cardano-cli conway query stake-address-info --testnet-magic 42 --address stake_test1uqjmy360gwmmdh02jeez2xunuanu35vvxzg94rdqa44svdsg3wuvt
[
    {
        "address": "stake_test1uqjmy360gwmmdh02jeez2xunuanu35vvxzg94rdqa44svdsg3wuvt",
        "delegation": "pool16nfsdtcszpfquqx038q7uz9ycvktnkr5r8xs6vs27uslqj3yw5k",
        "delegationDeposit": 0,
        "rewardAccountBalance": 0
    }
]%
```
It would be stellar to also include drep delegation on the output. Something like 

```
cardano-cli conway query stake-address-info --testnet-magic 42 --address stake_test1uqjmy360gwmmdh02jeez2xunuanu35vvxzg94rdqa44svdsg3wuvt
[
    {
        "address": "stake_test1uqjmy360gwmmdh02jeez2xunuanu35vvxzg94rdqa44svdsg3wuvt",
        "stakeDelegation": "pool16nfsdtcszpfquqx038q7uz9ycvktnkr5r8xs6vs27uslqj3yw5k",
        "voteDelegation": "cf09b59e134fa14e48da39b552c02299a054d7c8b895b3d827453672",
        "delegationDeposit": 0,
        "rewardAccountBalance": 0
    }
]%
```
```
cardano-cli conway query stake-address-info --testnet-magic 42 --address stake_test1uqjmy360gwmmdh02jeez2xunuanu35vvxzg94rdqa44svdsg3wuvt
[
    {
        "address": "stake_test1uqjmy360gwmmdh02jeez2xunuanu35vvxzg94rdqa44svdsg3wuvt",
        "stakeDelegation": "pool16nfsdtcszpfquqx038q7uz9ycvktnkr5r8xs6vs27uslqj3yw5k",
        "voteDelegation": "alwaysAbstain",
        "delegationDeposit": 0,
        "rewardAccountBalance": 0
    }
]%
```

**Comment by carlhammann** [comment]
It seems this issue requires some work in `cardano-api` and `ouroboros-consensus` as well. This is my investigation:

- The vote delegation of a stake address [is tracked](https://github.com/input-output-hk/cardano-ledger/blob/a505e7a4b51c61c2be103855d55e18df39ec1edd/libs/cardano-ledger-core/src/Cardano/Ledger/UMap.hs#L186) by the ledger in the form of an element of the type [`DRep c`](https://github.com/input-output-hk/cardano-ledger/blob/a505e7a4b51c61c2be103855d55e18df39ec1edd/libs/cardano-ledger-core/src/Cardano/Ledger/DRep.hs#L46).
- There is no query in the `cardano-api` that takes a stake address (or something like that) and returns the associated vote delegation. In fact, all queries defined in [`Cardano.Api.Query.Expr`](https://github.com/input-output-hk/cardano-api/blob/6d91127efc127c838689e011f67618d3cd2ffe4b/cardano-api/internal/Cardano/Api/Query/Expr.hs#L20) only have `DRep`s as part of their results if  they are already there in the inputs.
- The queries in `cardano-api` are implemented in terms of corresponding queries in `ouroboros-consensus`. For example [`queryStakeAddresses`](https://github.com/input-output-hk/cardano-api/blob/6d91127efc127c838689e011f67618d3cd2ffe4b/cardano-api/internal/Cardano/Api/Query/Expr.hs#L148) is implemented in terms of [`getFilteredDelegationsAndRewardAccounts`](https://github.com/input-output-hk/ouroboros-consensus/blob/682265a404272ec39118857675a10be89b9a2fec/ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Query.hs#L652).
- Drilling deeper into the implementation of that last function, we see that it disregards the `DRep`s associated with a staking credential, and only returns the stake delegation, rewards, and deposits. In order to extract the `DRep`, it would have to use the function [`umElemDRep`](https://github.com/input-output-hk/cardano-ledger/blob/a505e7a4b51c61c2be103855d55e18df39ec1edd/libs/cardano-ledger-core/src/Cardano/Ledger/UMap.hs#L327), which is used nowhere in `ouroboros-consensus`. I therefore conclude that there is no query in `ouroboros-consensus` that returns the data we want.

Does this assessment seem plausible? If yes, I'll start working on PRs to `ouroboros-consensus` and `cardano-api` before this.
