### ISSUE TITLE
Clarification of deposit(s) associated with a staking credential

### ISSUE THREAD

**Issue by carlhammann** [input-output-hk/cardano-cli#579]
This is my attempt to synthesize my knowledge (or rather, questions) related to issues #417 and #353. Both of these issues are quite old, both I had at some point "solved" with a PR only to reopen them later. Since they're related, I'll close them upon opening this.

It's about the `cardano-cli conway query stake-address-info` query. Among other information associated to a staking address, it also returns the deposit(s). There are (at least?) two kinds of deposits relevant here: The delegation deposit, and governance action deposits.

When I last looked into this, it was unclear
- whether it is possible (or even desirable) to obtain these deposits separately,
- whether the "delegation deposit" the query returns (sh|c)ould be the the actual deposit made, the minimal such deposit at the time of delegation, or the current such minimum, and
- whether and how the ledger even stores these data on a per-address basis, and how to query them.

I suggest answering these questions before taking another stab at this command.

**Comment by gitmachtl** [comment]
It would be good to have individual returns for the different kinds of deposits imo:

* the key deposit value (which is currently a bit confusing being returned as `delegationDeposit` entry). maybe renaming this to `keyDeposit` or `addressDeposit` ? 
* the vote delegation to the DRep-ID or always-abstain/no-confidence
* the governance action deposit which is currently locked

because all three of those are providing totally different purposes. 

The keyDeposit is actually sent out and stored for later "recovery", same with the actionDeposit. We need the exact keyDeposit value to generate the  correct stakeAddressRetirement-Certificate later on.

**Comment by smelc** [comment]
cc @CarlosLopezDeLara
