### ISSUE TITLE
Missing File Required by Governance

### ISSUE THREAD

**Issue by Ranchhand87** [input-output-hk/cardano-cli#769]
This repo is missing CHANGELOG.MD

This document is required per OSC Governance. https://intersect.gitbook.io/open-source-committee/policies/governance

**Comment by rdlrt** [comment]
https://github.com/IntersectMBO/cardano-cli/blob/main/cardano-cli/CHANGELOG.md

**Comment by smelc** [comment]
cc @CarlosLopezDeLara

**Comment by CarlosLopezDeLara** [comment]
@smelc @Ranchhand87 

CHANGELOG.MD for the cardano-cli package is in  https://github.com/IntersectMBO/cardano-cli/blob/main/cardano-cli/CHANGELOG.md

Which seems to meet the requirement : 

> A CHANGELOG (if the project includes multiple packages or similar, then one CHANGELOG per package may be more appropriate)

We could put it at the top level since (for now) the repository includes only `cardano-cli `package.   I don't know if that move could break any of the scripts used in, for example, tagging or releasing cardano-cli.

**Comment by Ranchhand87** [comment]
One Changelog per package is acceptable. If possible, a CHANGELOG.MD on the main page would be desirable, as it is easier to verify. If this would break the current systems, Please advise. Thanks!

**Comment by carbolymer** [comment]
Yeah that would break our release scripts. Can be a top level changelog a symlink to the cli's one: https://github.com/IntersectMBO/cardano-cli/tree/mgalazyn/chore/add-changelog ?
PR: https://github.com/IntersectMBO/cardano-cli/pull/770

**Comment by Ranchhand87** [comment]
@carbolymer That seems like a great approach. Creating a mainline Changelog that links to the more specific ones will work. Thank you.
