### ISSUE TITLE
[FR] - QoL feature: display txhash on command line after submitting tx

### ISSUE THREAD

**Issue by ptrdsh** [input-output-hk/cardano-cli#896]
**Internal/External**
~~*Internal*   if an IOHK staff member.~~
*External*   otherwise.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
`cardano-cli conway transaction submit` currently only outputs `Transaction successfully submitted` on the command line. Would be very handy to add the txHash of the submitted tx to the output, plus maybe even an overview of the outputs created (similar to how `query utxo` does it).

**Comment by smelc** [comment]
cc @CarlosLopezDeLara

**Comment by CarlosLopezDeLara** [comment]
Not so sure about the best way to print the information about the outputs, but printing the `TxId` should be very straight forward. I think we can start with that.  

- With this, users can follow-up with `query utxo --tx-in TxId#TxIx` to get the details, which might be more desirable since `query utxo --tx-in`  will only succeed once the transaction has been added to a block. Before that, the transaction may still fail i.e. because `--invalid-hereafter` is reached before the transaction made it to a block.

Let's think about how could we print the outputs info and what sorts of warnings should be put in place.

**Comment by Jimbo4350** [comment]
> Would be very handy to add the txHash of the submitted tx to the output, plus maybe even an overview of the outputs created (similar to how query utxo does it)

Why do you need this information? What do you intend to do with it?

**Comment by ptrdsh** [comment]
Ehm.. didn't expect that question, but I guess in short - it's the "thing" I made. I simply like to know what I paid for.

More concretely: track the tx's inclusion in a block, copy the hash to share it, ...

**Comment by ptrdsh** [comment]
Can I help in some way to make this happen?

**Comment by smelc** [comment]
@ptrdsh> we're good, this is going to happen; corresponding PR will be merged soon: https://github.com/IntersectMBO/cardano-cli/pull/925

You can give feedback on the chosen output format if you wish (see the PR's descripion).
